### ISSUE TITLE
Fails to correctly parse multi-line messagess

### ISSUE THREAD

**Issue by tfogwill** [EasyPost/syslog-rfc5424-parser#7]
RFC5424 allows MSG to be any octet string and thus to include newline characters.  syslog-rfc5424-parser does not parse beyond the first newline character - i.e. it only parses the first line of the input.

**Comment by Roguelazer** [comment]
This is actually intentional, since our primary use-case is parsing newline-delimited syslog messages (and since we primarily write using stream-mode, newline-delimited syslog sockets, it's impossible for us to ever generate such data).

If I did add multiline support, it would probably be behind some kind of optional flag.

**Comment by Roguelazer** [comment]
This is resolved in version 0.2.0, coming soon to a PyPI near you.
